[deps]
statsmodels = "<=0.13.0"
dandi = ""
pygments = ">=2.4.1"
pynwb = "2.3.1"
fsspec = ""
beautifulsoup4 = ""
python = "=3.9"
hdmf = "=3.4.7"
requests = ""
boto3 = "=1.17.21"
h5py = ""
pytables = ""
scikit-image = ""

[pip.deps]
allensdk = "@https://github.com/brendanjohnharris/AllenSDK/archive/refs/tags/v2.19.zip"
